/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.

 make -f Makefile.disp
 */

#include "disp.h"

int train[10][4];

int *
disponible_1_svc(int *fila, struct svc_req *rqstp)
{
	static int  result;

	if (train[*fila - 1][*fila -1] == 0){
		train[*fila - 1][*fila - 1] = 1;
		result = 1;
		return (&result);
	}
	else{
		result = 0;
		return &result;
	}
}
