/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdlib.h>
#include <stdio.h>
#include "disp.h"

int main (int argc, char *argv[]) {

	char *host;
	CLIENT *cl;
	int row;
	int column;
	int *result_1;
	char **result_2;
	char *vagon_1_arg;
	char temp[3];
	char row_column[4];

	/* Verificación de los argumentos de entrada*/ 
	if ((argc != 6) || (strcmp(argv[2],"-f") != 0) || (strcmp(argv[4],"-c") != 0)){
		printf ("Error en los argumentos de entradas");
		exit (1);
	}

	/* Verificación de un valor válido para el número de fila*/
	else if (atoi(argv[3]) > 10 || atoi(argv[3]) < 1 ){
		printf ("Error: Número de fila inválido");
		exit (1);
	}

	/* Verificación de un valor válido para el número de columna*/
	else if (atoi(argv[5]) > 4 || atoi(argv[5]) < 1 ){
		printf ("Error: Número de columna inválido");
		exit (1);
	}

	/* Asignación de las variables de entrada*/
	host = argv[1];
	row = atoi(argv[3]);
	column = atoi(argv[5]);

	//strcpy(row_column,argv[3]);
	//strcat(row_column," ");
	//strcat(row_column,argv[5]);

	/* Crea el cliente*/
	cl = clnt_create (host, DISPONIBLEPROG, DISPONIBLEVERS, "tcp");
	if (cl == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	while (1){

		/* Verifica si el puesto está disponible */
		result_1 = disponible_2(&row,cl);

		if (result_1 == (int *) NULL) {
			clnt_perror (cl, "call failed");
			break;
		}
		else if (*result_1 == 1){
			printf("El puesto fila %d columna %d ha sido reservado\n", row, column);
			break;
		}
		else if (*result_1 == 0){

			result_2 = vagon_2((void*)&vagon_1_arg,cl);
			if (result_2 == (char **) NULL) {
				clnt_perror (cl, "call failed");
			}

			if (strcmp(*result_2,"") == 0){

				printf("El vagón está completo.\n");
				break;
							}
			else {
				printf("El puesto fila %d columna %d está ocupado\nPuestos disponibles:\n%s\n", row, column, *result_2);
				break;
			}

		}
	}

	clnt_destroy(cl);
	exit (0);
}
