/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "reserva_bol.h"

int * is_available_2_svc(char **argp, struct svc_req *rqstp) {
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char ** seats_2_svc(void *argp, struct svc_req *rqstp){

	static char *result;
	char buffer [170]; 

	strcpy(buffer,"");
	for (i=0;i<10;i++){
		for (j=0;j<4;j++){
			if (train[i][j]==0){
				sprintf(temp,"%d",i+1);
				strcat(buffer,temp);
				strcat(buffer," ");
				sprintf(temp,"%d",j+1);
				strcat(buffer,temp);
				strcat(buffer,"\n");
			}
		}
	strcpy(result,buffer);
	return &result;
	return &result;
}
