/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RESERVA_BOL_H_RPCGEN
#define _RESERVA_BOL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RESERVA_BOL_PROG 99
#define RESERVA_BOL_VERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define IS_AVAILABLE 1
extern  int * is_available_2(char **, CLIENT *);
extern  int * is_available_2_svc(char **, struct svc_req *);
#define SEATS 2
extern  char ** seats_2(void *, CLIENT *);
extern  char ** seats_2_svc(void *, struct svc_req *);
extern int reserva_bol_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IS_AVAILABLE 1
extern  int * is_available_2();
extern  int * is_available_2_svc();
#define SEATS 2
extern  char ** seats_2();
extern  char ** seats_2_svc();
extern int reserva_bol_prog_2_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RESERVA_BOL_H_RPCGEN */
