/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "reserva_bool.h"

bool_t
xdr_seat (XDR *xdrs, seat *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->row))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->column))
		 return FALSE;
	return TRUE;
}
