/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "reserva_bool.h"

int train[10][4] = {{0}};

int *
make_reservation_3_svc(char **row_column, struct svc_req *rqstp)
{
	static int  result;

	char *token;
	int row, column;

	token = strtok(*row_column, " ");
	row = atoi(token);
	token = strtok(NULL, " ");
	column = atoi(token);

	if (train[row - 1][column -1] == 0){
		train[row - 1][column - 1] = 1;
		result = 1;
		return (&result);
	}
	else{
		result = 0;
		return &result;
	}
}

int *
available_3_svc(char **row_column, struct svc_req *rqstp)
{
	static int  result;

	char *token;
	int row, column;

	token = strtok(*row_column, " ");
	row = atoi(token);
	token = strtok(NULL, " ");
	column = atoi(token);

	if (train[row - 1][column -1] == 0){
		result = 1;
		return (&result);
	}
	else{
		result = 0;
		return &result;
	}
}
